CpuShip():setFaction("Human Navy"):setCallSign("Human Navy"):addBroadcast(2, "test0")
CpuShip():setFaction("Independent"):setCallSign("Independent"):addBroadcast(2, "test1")
CpuShip():setFaction("Kraylor"):setCallSign("Kraylor"):addBroadcast(2, "Kraylor")
CpuShip():setFaction("Arlenians"):setCallSign("Arlenians"):addBroadcast(2, "Arlenians")
CpuShip():setFaction("Exuari"):setCallSign("Exuari"):addBroadcast(2, "Exuari")
CpuShip():setFaction("Ghosts"):setCallSign("Ghosts"):addBroadcast(2, "Ghosts")
CpuShip():setFaction("Ktlitans"):setCallSign("Ktlitans"):addBroadcast(2, "Ktlitans")
CpuShip():setFaction("TSN"):setCallSign("TSN"):addBroadcast(2, "TSN")
CpuShip():setFaction("USN"):setCallSign("USN"):addBroadcast(2, "USN")
CpuShip():setFaction("CUF"):setCallSign("CUF"):addBroadcast(2, "CUF")